name: Test & Coverage

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .#test
      # - run: nix flake check --all-systems --print-build-logs